/*
 * Hinatazaka API
 *
 * 日向坂46を題材にしたサンプルAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// AuthApiRouter defines the required methods for binding the api requests to a responses for the AuthApi
// The AuthApiRouter implementation should parse necessary information from the http request, 
// pass the data to a AuthApiServicer to perform the required actions, then write the service results to the http response.
type AuthApiRouter interface { 
	GetAuth(http.ResponseWriter, *http.Request)
	GetCallback(http.ResponseWriter, *http.Request)
}
// HinatazakaApiRouter defines the required methods for binding the api requests to a responses for the HinatazakaApi
// The HinatazakaApiRouter implementation should parse necessary information from the http request, 
// pass the data to a HinatazakaApiServicer to perform the required actions, then write the service results to the http response.
type HinatazakaApiRouter interface { 
	DeleteMembersId(http.ResponseWriter, *http.Request)
	GetDiscographyId(http.ResponseWriter, *http.Request)
	GetMemberId(http.ResponseWriter, *http.Request)
	GetMembers(http.ResponseWriter, *http.Request)
	PostMembers(http.ResponseWriter, *http.Request)
	PutMembersId(http.ResponseWriter, *http.Request)
}


// AuthApiServicer defines the api actions for the AuthApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type AuthApiServicer interface { 
	GetAuth() (interface{}, error)
	GetCallback() (interface{}, error)
}


// HinatazakaApiServicer defines the api actions for the HinatazakaApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type HinatazakaApiServicer interface { 
	DeleteMembersId(string) (interface{}, error)
	GetDiscographyId(string) (interface{}, error)
	GetMemberId(int64) (interface{}, error)
	GetMembers() (interface{}, error)
	PostMembers(Member) (interface{}, error)
	PutMembersId(string, Member) (interface{}, error)
}
