/*
 * Hinatazaka API
 *
 * 日向坂46を題材にしたサンプルAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// AuthApiService is a service that implents the logic for the AuthApiServicer
// This service should implement the business logic for every endpoint for the AuthApi API.
// Include any external packages or services that will be required by this service.
type AuthApiService struct {
}

// NewAuthApiService creates a default api service
func NewAuthApiService() AuthApiServicer {
	return &AuthApiService{}
}

// GetAuth -
func (s *AuthApiService) GetAuth() (interface{}, error) {
	// TODO - update GetCallback with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetCallback' not implemented")
}

// GetCallback - Your GET endpoint
func (s *AuthApiService) GetCallback() (interface{}, error) {
	// TODO - update GetCallback with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetCallback' not implemented")
}
