/*
 * Hinatazaka API
 *
 * 日向坂46を題材にしたサンプルAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	_ "github.com/lib/pq"

	database "github.com/GIT_USER_ID/GIT_REPO_ID/database"
	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/openapi"
)

func main() {
	database.SetUp()
	defer database.DB.Close()

	AuthApiService := openapi.NewAuthApiService()
	AuthApiController := openapi.NewAuthApiController(AuthApiService)

	HinatazakaApiService := openapi.NewHinatazakaApiService()
	HinatazakaApiController := openapi.NewHinatazakaApiController(HinatazakaApiService)

	router := openapi.NewRouter(AuthApiController, HinatazakaApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
