/*
 * Hinatazaka API
 *
 * 日向坂46を題材にしたサンプルAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	// HinatazakaApiService := openapi.NewHinatazakaApiService()
	// HinatazakaApiController := openapi.NewHinatazakaApiController(HinatazakaApiService)
	DefaultMockService := openapi.NewDefaultMockService()
	HinatazakaApiController := openapi.NewHinatazakaApiController(DefaultMockService)

	router := openapi.NewRouter(HinatazakaApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
