/*
 * Hinatazaka API
 *
 * 日向坂46を題材にしたサンプルAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A HinatazakaApiController binds http requests to an api service and writes the service results to the http response
type HinatazakaApiController struct {
	service HinatazakaApiServicer
}

// NewHinatazakaApiController creates a default api controller
func NewHinatazakaApiController(s HinatazakaApiServicer) Router {
	return &HinatazakaApiController{ service: s }
}

// Routes returns all of the api route for the HinatazakaApiController
func (c *HinatazakaApiController) Routes() Routes {
	return Routes{ 
		{
			"GetDiscographyId",
			strings.ToUpper("Get"),
			"/discography/{id}",
			c.GetDiscographyId,
		},
		{
			"GetMemberId",
			strings.ToUpper("Get"),
			"/member/{id}",
			c.GetMemberId,
		},
		{
			"PostMemberId",
			strings.ToUpper("Post"),
			"/member/{id}",
			c.PostMemberId,
		},
	}
}

// GetDiscographyId - Your GET endpoint
func (c *HinatazakaApiController) GetDiscographyId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.GetDiscographyId(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// GetMemberId - 
func (c *HinatazakaApiController) GetMemberId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id, err := parseIntParameter(params["id"])
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.GetMemberId(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// PostMemberId - 
func (c *HinatazakaApiController) PostMemberId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	member := &Member{}
	if err := json.NewDecoder(r.Body).Decode(&member); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.PostMemberId(id, *member)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
