/*
 * sample API
 *
 * This is sample.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Pets struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	// pet status in the store
	Status string `json:"status,omitempty"`
}
