generate-golang:
	openapi-generator generate -i openapi.yml -g go-server -o ../golang --additional-properties=sourceFolder=openapi

generate-react:
	openapi-generator generate -i openapi.yml -g typescript-axios -o ../react/api

